### ISSUE TITLE
Map breaks if no :center is provided

### ISSUE THREAD

**Issue by BigBadaboom** [NathanAP/vue-google-maps-community-fork#28]
If you don't provide a `center` attribute, the map will not render properly.

- If you don't provide it at all, the map won't render (you'll get a grey rectangle)
- if you provide the center another way, eg via `options`, the map will render but no markers will render

See: https://stackblitz.com/edit/vue-google-maps-marker-uhwl21?file=src%2Fcomponents%2FComponentWithMap.vue

**Expected result**
Map should render the same no matter how you provide the `center`

**Actual result**
If you don't specify a `center` ***attribute***, the map won't render properly

**Workaround**
I supplied a dummy `center` atrtribute and overrode it via `options`.

**Device or enviroment**

- In which OS are you seeing this bug? Examples: Windows 11, Ubuntu, iOS.
Windows 10 x64
- If it is relevant, what browser are you? Examples: Chrome, Safari, Opera.
Chrome
- What is your npm version? You can check using npm -v.
8.19.2
- What is your vue version? You can check using npm list.
3
- What is your vue-google-maps-community-fork version? You can check using npm list.
0.1.6

**Comment by NathanAP** [comment]
Hello! Thanks for reporting and sorry for the delay on your answer.

- IMO we need to understand why this prop is required and not defined with a default value instead. Maybe its because the deep codes use the `center` prop to make the map move? 🤔
- If we don't find a plausible reason I believe we could change the `required: true` from `map.vue line 22` ([here](https://github.com/NathanAP/vue-google-maps-community-fork/blob/main/src/components/map.vue#L22)) with `default: { lat: 0, lng: 0}`, right?

**Comment by BigBadaboom** [comment]
@NathanAP Sounds like a reasonable approach.

**Comment by felixranesberger** [comment]
I can provide a pull request for this issue :)

**Comment by NathanAP** [comment]
> I can provide a pull request for this issue :)

Feel free to do it! I'm a bit busy these days to be honest, so I would appreciate your help :)

**Comment by BigBadaboom** [comment]
Thanks!
